### ISSUE TITLE
Windows 10 asar unpacking

### ISSUE THREAD

**Issue by firnen0** [AryToNeX/Glasscord#44]
There doesn't seem to be any asar unpacking tool for windows and the only tool I can find online can only be installed on linux. Is there anyway to install Glasscord on windows now?

**Comment by PoorPocketsMcNewHold** [comment]
> Now you need to get the package.json file from the app.asar file. The best and quickest way to extract it via the asar command line tool.
> 
> **If you don't have it, install it via sudo npm install -g --engine-strict asar.**

There is. It is explained in the README.md https://nodejs.org
Request to close this comment.

**Comment by nakami** [comment]
First, you have to install `node.js` and use the included `npm` package manager to install the package `asar`.

Then, install `asar` via an administrator powershell:

> npm install -g --engine-strict asar

Now you can open a powershell in the directory and execute asar:

> PS C:\Users\$user\AppData\Local\Discord\app-0.0.306\resources> **asar ef app.asar package.json**

(the path in the beginning is where im at, since this is my discord version/directory)


@PoorPocketsMcNewHold Windows has no sudo command, you'll need an administractor powershell prompt, so this line is confusing for windows users.

**Comment by complex-hub** [comment]
In case @firnen0 doesn't want to use the powershell command line, [7zip has a plugin that alows it to open .asar files.](https://www.tc4shell.com/en/7zip/asar/) This comes with the benefit that you can do the extraction via a GUI.
![Anotação 2020-06-28 145609](https://user-images.githubusercontent.com/53913349/85954833-b1384a80-b950-11ea-8464-f016f6276323.jpg)

**Comment by AryToNeX** [comment]
Inactive, closing as it's a non-issue
