### ISSUE TITLE
Broken osx titlebar on linux and windows when applied to discord.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [AryToNeX/Glasscord#46]
**Describe the bug**
People has been reporting having the OSX titlebar injection to not work. I´ve personally tried it myself and did confirmed it to not work on my discord installation. It correctly create additional space for the titlebar button, but it doesn´t create the buttons in itself in that area anymore. https://canary.discordapp.com/channels/696696149301657640/696743152190488617/724873810821775421

**Note:** This issue section is for Glasscord only!
DO NOT report other apps' issues.
More specifically, DO NOT REPORT ANYTHING RELATED
SPECIFICALLY TO GLASSTRON OR GLASSCORD MODULES HERE!

**To Reproduce**
1. Set your glasscord theme to use this variable in `:root` : `--glasscord-titlebar: osx;`
2. The glasscord theme should ask you to reload Discord in order to implement the modified titlebar.
3. See bug.

**Expected behavior**
A working OSX titlebar should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: GNU/Linux. Also reported on Windows 10 copies.
 - Discord version: Canary 62404 also reported on other discord instances.
 - Glasscord version: Source and 0.2
 - Other Discord mods used: Powercord for my case.

**Comment by PoorPocketsMcNewHold** [comment]
The user Sylpha#9666 (133911329839775744) answered this : https://canary.discordapp.com/channels/696696149301657640/696743152190488617/726943618723479554

> I had a small issue with it using it at first but it worked consistently after a few reloads

**Comment by AryToNeX** [comment]
The OSX titlebar is working consistently here. Sometimes, refreshing the window will make the buttons pop up, either by maximizing/unmaximizing, dragging, focus change, etc.

The popup may not appear if the state change is done within the first 10 seconds since Discord started up (that's to prevent the "ghost popup" bug we had back in 0.0.7.1)

Upon further inspection I can confirm, however, that all of the custom titlebars are indeed working on Windows and on Linux.
