### ISSUE TITLE
Not working effects

### ISSUE THREAD

**Issue by Ibirtem** [AryToNeX/Glasscord#50]
Uh... Maybe i do something wrong? Glasscord seems to be loading as it cannot be deleted when Discord is open. Do i need turn on  transparency in BandagedBD? If so, even so it doesn't work. Just clear Discord without frosted effects.
![image](https://user-images.githubusercontent.com/54157950/88166915-b3748880-cc20-11ea-969e-46e63eb7ad0a.png)

**Comment by PoorPocketsMcNewHold** [comment]
Multiple mistakes : 

*   Incorrect name. You’ve named the original `package.json` as `package.original.json.json` instead of the correct `package.original.json`.
*   You’ve installed it in the wrong folder. It should be in the `%AppData%/local/discord/app-*` folder, instead of Roaming.
*   _Surely due to the wrong folder._ According to the content of the package.json, It isn’t the original one which is modified by BandagedBetterDiscord.

Outside that, to answer your questions : 

*   No, You should not activate the BandagedBetterDiscord transparency effect. This will break the Glasscord capabilities to request blurring effects from your Windows Compositor.

Requesting to close this issue.

**Comment by Ibirtem** [comment]
oh... Thanks! This works!
