### ISSUE TITLE
Electron Security Practices

### ISSUE THREAD

**Issue by night** [AryToNeX/Glasscord#56]
Upon reviewing this project's injection code, it appears it disables a security feature implemented by Discord to ensure remote code is sufficiently sandboxed from the operating system.

```javascript
        options.webPreferences.contextIsolation = false;
```

This software disables Electron's context isolation, which forces browser code to run in a separate context from main window code. This prevents attackers from doing things like polluting prototypes which may expose access to restricted functions that escalate access to execute arbitrary commands.

Security of Electron is not to be taken lightly as there are many foot-guns. By releasing software like this and encouraging people to install it, you are putting users at risk without taking proper steps to keep Electron secure. I would strongly encourage you to read up on the best security practices for Electron at https://www.electronjs.org/docs/tutorial/security and apply those to this project.

**Comment by AryToNeX** [comment]
I am aware of the situation, and fixing this comes with many challenges (it may not be doable without a complete rewrite of the core parts of the project).

Of course allowing context isolation is somewhat "easy"; as Glasscord is mainly a "main process" modification that (ab)uses `webContents.executeJavaScript()`, very little parts of the project will straight up break from this change.
However, those very little parts of the project are actually the very important ones: I am referring to the CSS loader and to the CSS watchdog.
Those two components run in the renderer process (one in the preload, the other via `executeJavaScript`) and both of them make use of the Node `require()` function, which I pass from the preload script to the so-called "main world" via the `GlasscordApi` object (as this modification works on several applications it was necessary to preserve the Node require function from being removed or modified (and filtered) by apps I want to modify).
Now this is a security vulnerability in itself, as I am exposing the require function anyway, regardless of the `useNodeIntegration` flag, and I am well aware of it too.
Patching this vulnerability and allowing context isolation could also break other applications; as Glasscord is, despite its name, a general Electron app modification, it has to be consistent and contain as little "app-specific" code as possible, and preferably in modules only.
And yes, I have to discuss a bit about modules. They are loaded in the main process, and from there they interface to the renderer via the `webContents.executeJavaScript()` method. While this is not very limiting to them (as the main process is not affected by this change), their calls to the renderer may be; I don't know which things they're going to `require()` in advance, and so I need to expose the stuff "heuristically" because I can't give them the `require()` function.

This will take up a lot of effort to fix. I will try. In the meantime, please feel free to discuss this issue more.

CC: @Bowser65 @rauenzi (guess you guys are in this hell too)

**Comment by night** [comment]
> Those two components run in the renderer process (one in the preload, the other via executeJavaScript) and both of them make use of the Node require() function, which I pass from the preload script to the so-called "main world" via the GlasscordApi object (as this modification works on several applications it was necessary to preserve the Node require function from being removed or modified (and filtered) by apps I want to modify).
Now this is a security vulnerability in itself, as I am exposing the require function anyway, regardless of the useNodeIntegration flag, and I am well aware of it too.

I would recommend checking out the (experimental) context bridge: https://www.electronjs.org/docs/api/context-bridge

This will allow you to essentially expose and proxy most values, even functions, between contexts. For operations which are not happening at high velocity this is probably enough to create a barrier between the worlds. You generally want to apply the [PoLP](https://en.wikipedia.org/wiki/Principle_of_least_privilege) here too by exposing specific data/methods to perform only specific tasks required. In other words, avoid generic exposure like `require('fs')`.

> Patching this vulnerability and allowing context isolation could also break other applications; as Glasscord is, despite its name, a general Electron app modification, it has to be consistent and contain as little "app-specific" code as possible, and preferably in modules only.

I haven't tried using context bridge with node enabled or context isolation disabled, but if it does not work across all apps you could try detecting BrowserWindow options and mimicking the same data across different BrowserWindow options. That could involve polyfilling something to the window.

> And yes, I have to discuss a bit about modules. They are loaded in the main process, and from there they interface to the renderer via the webContents.executeJavaScript() method. While this is not very limiting to them (as the main process is not affected by this change), their calls to the renderer may be; I don't know which things they're going to require() in advance, and so I need to expose the stuff "heuristically" because I can't give them the require() function.

It's probably a smart thing to break `require` for modules, to be honest. They shouldn't need that kind of access, and if they do need some amount of access, it might be wise to expose a limited API for them to utilize instead.

**Comment by AryToNeX** [comment]
I made a new branch called `fix-context-isolation` to prepare the code as much as possible to "support" it (before flipping the switch, that is).
I already submitted a patch for the CSS loader part there; if that works, I will be looking at the CSS watchdog (which, to me, seems like the harder part of this work).

As Electron documentation says, the `window` object on the preload script is not the same as the `window` object in the main world, so I need a way to execute stuff on the main world before the actual page loads up (the preload script was great for this purpose, but since it's isolated, I cannot really use it now)

**Comment by AryToNeX** [comment]
@night The `fix-context-isolation` branch is ready for testing. If everything works as intended, I will merge it and close this issue.

**Comment by AryToNeX** [comment]
The issue is now closed as I tested the client mod on vanilla Discord and vanilla VSCode and it works with no noticeable issues. Core modules work as intended too. I guess it's good enough for now.

If you have other questions and things to point out, we can reopen this issue.
